module.exports = [{
  name: '05AB1E',
  engine: 'tryit',
  id: '05ab1e',
}, {
  name: '2sable',
  engine: 'tryit',
  id: '2sable',
}, {
  name: '3var',
  engine: 'tryit',
  id: '3var',
}, {
  name: '99',
  engine: 'tryit',
  id: '99',
}, {
  name: 'Actually',
  engine: 'tryit',
  id: 'actually',
}, {
  name: 'Ada',
  engine: 'ideone',
  id: '7',
}, {
  name: 'Arcyóu',
  engine: 'tryit',
  id: 'arcyou',
}, {
  name: 'Aubergine',
  engine: 'tryit',
  id: 'aubergine',
}, {
  name: 'AWK',
  engine: 'ideone',
  id: '104',
}, {
  name: 'Axo',
  engine: 'tryit',
  id: 'axo',
}, {
  name: 'bc',
  engine: 'ideone',
  id: '110',
}, {
  name: 'Beatnik',
  engine: 'tryit',
  id: 'beatnik',
}, {
  name: 'Beeswax',
  engine: 'tryit',
  id: 'beeswax',
}, {
  name: 'Befunge',
  engine: 'tryit',
  id: 'befunge',
}, {
  name: 'Befunge-98',
  engine: 'tryit',
  id: 'befunge-98',
}, {
  name: 'Brachylog',
  engine: 'tryit',
  id: 'brachylog',
}, {
  name: 'Brain-Flak',
  engine: 'tryit',
  id: 'brain-flak',
}, {
  name: 'brainbool',
  engine: 'tryit',
  id: 'brainbool',
}, {
  name: 'Brainfuck',
  engine: 'tryit',
  id: 'brainfuck',
}, {
  name: 'Brian & Chuck',
  engine: 'tryit',
  id: 'brian-chuck',
}, {
  name: 'Bubblegum',
  engine: 'tryit',
  id: 'bubblegum',
}, {
  name: 'Charcoal',
  engine: 'tryit',
  id: 'charcoal',
}, {
  name: 'Cheddar',
  engine: 'tryit',
  id: 'cheddar',
}, {
  name: 'Cinnamon Gum',
  engine: 'tryit',
  id: 'cinnamon-gum',
}, {
  name: 'CJam',
  engine: 'tryit',
  id: 'cjam',
}, {
  name: 'CLIPS',
  engine: 'ideone',
  id: '14',
}, {
  name: 'COBOL',
  engine: 'ideone',
  id: '118',
}, {
  name: 'Convex',
  engine: 'tryit',
  id: 'convex',
}, {
  name: 'Cy',
  engine: 'tryit',
  id: 'cy',
}, {
  name: 'Detour',
  engine: 'tryit',
  id: 'detour',
}, {
  name: 'Element',
  engine: 'tryit',
  id: 'element',
}, {
  name: 'ETA',
  engine: 'tryit',
  id: 'eta',
}, {
  name: 'evil',
  engine: 'tryit',
  id: 'evil',
}, {
  name: 'Factor',
  engine: 'ideone',
  id: 'Factor',
}, {
  name: 'Falcon',
  engine: 'ideone',
  id: 'Falcon',
}, {
  name: 'Fantom',
  engine: 'ideone',
  id: 'Fantom',
}, {
  name: 'FerNANDo',
  engine: 'tryit',
  id: 'fernando',
}, {
  name: 'FEU',
  engine: 'tryit',
  id: 'feu',
}, {
  name: '><>',
  engine: 'tryit',
  id: 'fish',
}, {
  name: 'Fission',
  engine: 'tryit',
  id: 'fission',
}, {
  name: 'Fission 2',
  engine: 'tryit',
  id: 'fission2',
}, {
  name: 'Foo',
  engine: 'tryit',
  id: 'foo',
}, {
  name: 'Forth',
  engine: 'ideone',
  id: 'Forth',
}, {
  name: 'Fourier',
  engine: 'tryit',
  id: 'fourier',
}, {
  name: 'GolfScript',
  engine: 'tryit',
  id: 'golfscript',
}, {
  name: 'Grime',
  engine: 'tryit',
  id: 'grime',
}, {
  name: 'Groovy',
  engine: 'ideone',
  id: '121',
}, {
  name: 'GS2',
  engine: 'tryit',
  id: 'gs2',
}, {
  name: 'Forth',
  engine: 'ideone',
  id: '107',
}, {
  name: 'Hexagony',
  engine: 'tryit',
  id: 'hexagony',
}, {
  name: 'Icon',
  engine: 'ideone',
  id: '16',
}, {
  name: 'Intercal',
  engine: 'ideone',
  id: '9',
}, {
  name: 'Jelly',
  engine: 'tryit',
  id: 'jelly',
}, {
  name: 'Jellyfish',
  engine: 'tryit',
  id: 'jellyfish',
}, {
  name: 'Julia',
  engine: 'tryit',
  id: 'julia',
}, {
  name: 'Labyrinth',
  engine: 'tryit',
  id: 'labyrinth',
}, {
  name: 'Logicode',
  engine: 'tryit',
  id: 'logicode',
}, {
  name: 'MarioLANG',
  engine: 'tryit',
  id: 'mariolang',
}, {
  name: 'MATL',
  engine: 'tryit',
  id: 'matl',
}, {
  name: 'Minkolang',
  engine: 'tryit',
  id: 'minkolang',
}, {
  name: 'Nice',
  engine: 'ideone',
  id: '25',
}, {
  name: 'Oasis',
  engine: 'tryit',
  id: 'oasis',
}, {
  name: 'Octave',
  engine: 'ideone',
  id: '127',
}, {
  name: 'Pike',
  engine: 'ideone',
  id: '19',
}, {
  name: 'Pip',
  engine: 'tryit',
  id: 'pip',
}, {
  name: 'pl',
  engine: 'tryit',
  id: 'pl',
}, {
  name: 'Prelude',
  engine: 'tryit',
  id: 'prelude',
}, {
  name: 'Purple',
  engine: 'tryit',
  id: 'purple',
}, {
  name: 'Pylons',
  engine: 'tryit',
  id: 'pylons',
}, {
  name: 'Pyth',
  engine: 'tryit',
  id: 'pyth',
}, {
  name: 'Rail',
  engine: 'tryit',
  id: 'rail',
}, {
  name: 'reticular',
  engine: 'tryit',
  id: 'reticular',
}, {
  name: 'Retina',
  engine: 'tryit',
  id: 'retina',
}, {
  name: 'Rotor',
  engine: 'tryit',
  id: 'rotor',
}, {
  name: 'sed',
  engine: 'tryit',
  id: 'sed',
}, {
  name: 'Seriously',
  engine: 'tryit',
  id: 'seriously',
}, {
  name: 'Sesos',
  engine: 'tryit',
  id: 'sesos',
}, {
  name: 'ShapeScript',
  engine: 'tryit',
  id: 'shapescript',
}, {
  name: 'Shtriped',
  engine: 'tryit',
  id: 'shtriped',
}, {
  name: 'S.I.L.O.S',
  engine: 'tryit',
  id: 'silos',
}, {
  name: '///',
  engine: 'tryit',
  id: 'slashes',
}, {
  name: 'Self-modifying Brainfuck',
  engine: 'tryit',
  id: 'smbf',
}, {
  name: 'Smalltalk',
  engine: 'ideone',
  id: '23',
}, {
  name: 'Snails',
  engine: 'tryit',
  id: 'snails',
}, {
  name: 'Snowman',
  engine: 'tryit',
  id: 'snowman',
}, {
  name: 'Stack Cats',
  engine: 'tryit',
  id: 'stackcats',
}, {
  name: 'Starry',
  engine: 'tryit',
  id: 'starry',
}, {
  name: 'Straw',
  engine: 'tryit',
  id: 'straw',
}, {
  name: 'SQL',
  engine: 'ideone',
  id: '40',
}, {
  name: 'Tcl',
  engine: 'ideone',
  id: '38',
}, {
  name: 'Thue',
  engine: 'tryit',
  id: 'thue',
}, {
  name: 'TRANSCRIPT',
  engine: 'tryit',
  id: 'transcript',
}, {
  name: 'Turtlèd',
  engine: 'tryit',
  id: 'turtled',
}, {
  name: 'Underload',
  engine: 'tryit',
  id: 'underload',
}, {
  name: 'V',
  engine: 'tryit',
  id: 'v',
}, {
  name: 'Vitsy',
  engine: 'tryit',
  id: 'vitsy',
}, {
  name: 'Whirl',
  engine: 'tryit',
  id: 'whirl',
}, {
  name: 'Whitespace',
  engine: 'ideone',
  id: '6',
}, {
  name: 'Woefully',
  engine: 'tryit',
  id: 'woefully',
}, {
  name: 'Yup',
  engine: 'tryit',
  id: 'yup',
}];
