module.exports = [{
  name: '05AB1E',
  engine: 'tryit',
  id: '05ab1e',
  slug: '05ab1e',
}, {
  name: '2sable',
  engine: 'tryit',
  id: '2sable',
  slug: '2sable',
}, {
  name: '3var',
  engine: 'tryit',
  id: '3var',
  slug: '3var',
}, {
  name: 'Nemerle',
  engine: 'ideone',
  id: '30',
  slug: 'nemerle',
}, {
  name: 'Actually',
  engine: 'tryit',
  id: 'actually',
  slug: 'actually',
}, {
  name: 'Ada',
  engine: 'ideone',
  id: '7',
  slug: 'ada',
}, {
  name: 'Arcyóu',
  engine: 'tryit',
  id: 'arcyou',
  slug: 'arcyou',
}, {
  name: 'Aubergine',
  engine: 'tryit',
  id: 'aubergine',
  slug: 'aubergine',
}, {
  name: 'AWK',
  engine: 'ideone',
  id: '104',
  slug: 'awk',
}, {
  name: 'Axo',
  engine: 'tryit',
  id: 'axo',
  slug: 'axo',
}, {
  name: 'bc',
  engine: 'ideone',
  id: '110',
  slug: 'bc',
}, {
  name: 'Beatnik',
  engine: 'tryit',
  id: 'beatnik',
  slug: 'beatnik',
}, {
  name: 'Beeswax',
  engine: 'tryit',
  id: 'beeswax',
  slug: 'beeswax',
}, {
  name: 'Befunge',
  engine: 'tryit',
  id: 'befunge',
  slug: 'befunge',
}, {
  name: 'Befunge-98',
  engine: 'tryit',
  id: 'befunge-98',
  slug: 'befunge-98',
}, {
  name: 'Brachylog',
  engine: 'tryit',
  id: 'brachylog',
  slug: 'brachylog',
}, {
  name: 'Brain-Flak',
  engine: 'tryit',
  id: 'brain-flak',
  slug: 'brain-flak',
}, {
  name: 'brainbool',
  engine: 'tryit',
  id: 'brainbool',
  slug: 'brainbool',
}, {
  name: 'Brainfuck',
  engine: 'tryit',
  id: 'brainfuck',
  slug: 'brainfuck',
}, {
  name: 'Brian & Chuck',
  engine: 'tryit',
  id: 'brian-chuck',
  slug: 'brian-chuck',
}, {
  name: 'Bubblegum',
  engine: 'tryit',
  id: 'bubblegum',
  slug: 'bubblegum',
}, {
  name: 'Charcoal',
  engine: 'tryit',
  id: 'charcoal',
  slug: 'charcoal',
}, {
  name: 'Cheddar',
  engine: 'tryit',
  id: 'cheddar',
  slug: 'cheddar',
}, {
  name: 'Cinnamon Gum',
  engine: 'tryit',
  id: 'cinnamon-gum',
  slug: 'cinnamon-gum',
}, {
  name: 'CJam',
  engine: 'tryit',
  id: 'cjam',
  slug: 'cjam',
}, {
  name: 'CLIPS',
  engine: 'ideone',
  id: '14',
  slug: 'clips',
}, {
  name: 'Convex',
  engine: 'tryit',
  id: 'convex',
  slug: 'convex',
}, {
  name: 'Cy',
  engine: 'tryit',
  id: 'cy',
  slug: 'cy',
}, {
  name: 'Detour',
  engine: 'tryit',
  id: 'detour',
  slug: 'detour',
}, {
  name: 'Element',
  engine: 'tryit',
  id: 'element',
  slug: 'element',
}, {
  name: 'ETA',
  engine: 'tryit',
  id: 'eta',
  slug: 'eta',
}, {
  name: 'evil',
  engine: 'tryit',
  id: 'evil',
  slug: 'evil',
}, {
  name: 'Factor',
  engine: 'ideone',
  id: '123',
  slug: 'factor',
}, {
  name: 'Falcon',
  engine: 'ideone',
  id: '125',
  slug: 'falcon',
}, {
  name: 'Fantom',
  engine: 'ideone',
  id: '92',
  slug: 'fantom',
}, {
  name: 'FerNANDo',
  engine: 'tryit',
  id: 'fernando',
  slug: 'fernando',
}, {
  name: 'FEU',
  engine: 'tryit',
  id: 'feu',
  slug: 'feu',
}, {
  name: '><>',
  engine: 'tryit',
  id: 'fish',
  slug: 'fish',
}, {
  name: 'Fission',
  engine: 'tryit',
  id: 'fission',
  slug: 'fission',
}, {
  name: 'Fission 2',
  engine: 'tryit',
  id: 'fission2',
  slug: 'fission2',
}, {
  name: 'Foo',
  engine: 'tryit',
  id: 'foo',
  slug: 'foo',
}, {
  name: 'Forth',
  engine: 'ideone',
  id: '107',
  slug: 'forth',
}, {
  name: 'Fourier',
  engine: 'tryit',
  id: 'fourier',
  slug: 'fourier',
}, {
  name: 'GolfScript',
  engine: 'tryit',
  id: 'golfscript',
  slug: 'golfscript',
}, {
  name: 'Grime',
  engine: 'tryit',
  id: 'grime',
  slug: 'grime',
}, {
  name: 'Groovy',
  engine: 'ideone',
  id: '121',
  slug: 'groovy',
}, {
  name: 'GS2',
  engine: 'tryit',
  id: 'gs2',
  slug: 'gs2',
}, {
  name: 'Hexagony',
  engine: 'tryit',
  id: 'hexagony',
  slug: 'hexagony',
}, {
  name: 'Icon',
  engine: 'ideone',
  id: '16',
  slug: 'icon',
}, {
  name: 'Intercal',
  engine: 'ideone',
  id: '9',
  slug: 'intercal',
}, {
  name: 'Jelly',
  engine: 'tryit',
  id: 'jelly',
  slug: 'jelly',
}, {
  name: 'Jellyfish',
  engine: 'tryit',
  id: 'jellyfish',
  slug: 'jellyfish',
}, {
  name: 'Julia',
  engine: 'tryit',
  id: 'julia',
  slug: 'julia',
}, {
  name: 'Labyrinth',
  engine: 'tryit',
  id: 'labyrinth',
  slug: 'labyrinth',
}, {
  name: 'Logicode',
  engine: 'tryit',
  id: 'logicode',
  slug: 'logicode',
}, {
  name: 'MarioLANG',
  engine: 'tryit',
  id: 'mariolang',
  slug: 'mariolang',
}, {
  name: 'MATL',
  engine: 'tryit',
  id: 'matl',
  slug: 'matl',
}, {
  name: 'Minkolang',
  engine: 'tryit',
  id: 'minkolang',
  slug: 'minkolang',
}, {
  name: 'Nice',
  engine: 'ideone',
  id: '25',
  slug: 'nice',
}, {
  name: 'Oasis',
  engine: 'tryit',
  id: 'oasis',
  slug: 'oasis',
}, {
  name: 'Octave',
  engine: 'ideone',
  id: '127',
  slug: 'octave',
}, {
  name: 'Oz',
  engine: 'ideone',
  id: '119',
  slug: 'oz',
}, {
  name: 'Pike',
  engine: 'ideone',
  id: '19',
  slug: 'pike',
}, {
  name: 'Pip',
  engine: 'tryit',
  id: 'pip',
  slug: 'pip',
}, {
  name: 'pl',
  engine: 'tryit',
  id: 'pl',
  slug: 'pl',
}, {
  name: 'Prelude',
  engine: 'tryit',
  id: 'prelude',
  slug: 'prelude',
}, {
  name: 'Purple',
  engine: 'tryit',
  id: 'purple',
  slug: 'purple',
}, {
  name: 'Pylons',
  engine: 'tryit',
  id: 'pylons',
  slug: 'pylons',
}, {
  name: 'Pyth',
  engine: 'tryit',
  id: 'pyth',
  slug: 'pyth',
}, {
  name: 'Rail',
  engine: 'tryit',
  id: 'rail',
  slug: 'rail',
}, {
  name: 'reticular',
  engine: 'tryit',
  id: 'reticular',
  slug: 'reticular',
}, {
  name: 'Retina',
  engine: 'tryit',
  id: 'retina',
  slug: 'retina',
}, {
  name: 'Rotor',
  engine: 'tryit',
  id: 'rotor',
  slug: 'rotor',
}, {
  name: 'sed',
  engine: 'tryit',
  id: 'sed',
  slug: 'sed',
}, {
  name: 'Seriously',
  engine: 'tryit',
  id: 'seriously',
  slug: 'seriously',
}, {
  name: 'Sesos',
  engine: 'tryit',
  id: 'sesos',
  slug: 'sesos',
}, {
  name: 'ShapeScript',
  engine: 'tryit',
  id: 'shapescript',
  slug: 'shapescript',
}, {
  name: 'Shtriped',
  engine: 'tryit',
  id: 'shtriped',
  slug: 'shtriped',
}, {
  name: 'S.I.L.O.S',
  engine: 'tryit',
  id: 'silos',
  slug: 'silos',
}, {
  name: '///',
  engine: 'tryit',
  id: 'slashes',
  slug: 'slashes',
}, {
  name: 'Self-modifying Brainfuck',
  engine: 'tryit',
  id: 'smbf',
  slug: 'smbf',
}, {
  name: 'Smalltalk',
  engine: 'ideone',
  id: '23',
  slug: 'smalltalk',
}, {
  name: 'Snails',
  engine: 'tryit',
  id: 'snails',
  slug: 'snails',
}, {
  name: 'Snowman',
  engine: 'tryit',
  id: 'snowman',
  slug: 'snowman',
}, {
  name: 'Stack Cats',
  engine: 'tryit',
  id: 'stackcats',
  slug: 'stackcats',
}, {
  name: 'Starry',
  engine: 'tryit',
  id: 'starry',
  slug: 'starry',
}, {
  name: 'Straw',
  engine: 'tryit',
  id: 'straw',
  slug: 'straw',
}, {
  name: 'SQL',
  engine: 'ideone',
  id: '40',
  slug: 'sql',
}, {
  name: 'Tcl',
  engine: 'ideone',
  id: '38',
  slug: 'tcl',
}, {
  name: 'Thue',
  engine: 'tryit',
  id: 'thue',
  slug: 'thue',
}, {
  name: 'TRANSCRIPT',
  engine: 'tryit',
  id: 'transcript',
  slug: 'transcript',
}, {
  name: 'Turtlèd',
  engine: 'tryit',
  id: 'turtled',
  slug: 'turtled',
}, {
  name: 'Underload',
  engine: 'tryit',
  id: 'underload',
  slug: 'underload',
}, {
  name: 'Unlambda',
  engine: 'ideone',
  id: '115',
  slug: 'unlambda',
}, {
  name: 'V',
  engine: 'tryit',
  id: 'v',
  slug: 'v',
}, {
  name: 'Vitsy',
  engine: 'tryit',
  id: 'vitsy',
  slug: 'vitsy',
}, {
  name: 'Whirl',
  engine: 'tryit',
  id: 'whirl',
  slug: 'whirl',
}, {
  name: 'Whitespace',
  engine: 'ideone',
  id: '6',
  slug: 'whitespace',
}, {
  name: 'Woefully',
  engine: 'tryit',
  id: 'woefully',
  slug: 'woefully',
}, {
  name: 'Yup',
  engine: 'tryit',
  id: 'yup',
  slug: 'yup',
}];
